/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.62
 * Generated at: 2017-12-06 06:11:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.userSystem;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("    <meta name=\"renderer\" content=\"webkit\">\r\n");
      out.write("    <title>ç»å½</title>\r\n");
      out.write("    <meta name=\"description\" content=\"äºä¼æ±äºä¼æ±äºä¼æ±äºä¼æ±äºä¼æ±äºä¼æ±äºä¼æ±äºä¼æ±äºä¼æ±äºä¼æ±äºä¼æ±äºä¼æ±äºä¼æ±äºä¼æ±äºä¼æ±äºä¼æ±äºä¼æ±äºä¼æ±äºä¼æ±äºä¼æ±äºä¼æ±äºä¼æ±\">\r\n");
      out.write("    <meta name=\"keywords\" content=\"å°ç¨åº,å¾®ä¿¡å°ç¨åº,é¤å­,æ¨¡ç,å°ç¨åºæ¨¡ç,å°ç¨åºåå\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("    <meta name=\"renderer\" content=\"webkit\">\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"./favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/base.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/index.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/reg-login.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!--å¯¼èªæ¡-->\r\n");
      out.write("<div class=\"navs-box\">\r\n");
      out.write("    <div class=\"navs w clearfix\">\r\n");
      out.write("        <a href=\"index.html\" class=\"fl\"><img src=\"./img/login.png\" alt=\"\"></a>\r\n");
      out.write("        <div class=\"server fl alertMenu\">\r\n");
      out.write("            <p class=\"arrow\">äº§å&æå¡</p>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <img src=\"./img/floor.png\" alt=\"\"><span>å¬å¸ä¼ä¸</span>\r\n");
      out.write("                    <p><span>ç§æ</span><span>é¤é¥®</span><span>ç§æ</span><span>ç§æ</span></p>\r\n");
      out.write("                    <ol>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                    </ol>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <img src=\"./img/floor.png\" alt=\"\"><span>å¬å¸ä¼ä¸</span>\r\n");
      out.write("                    <p><span>ç§æ</span><span>é¤é¥®</span><span>ç§æ</span><span>ç§æ</span></p>\r\n");
      out.write("                    <ol>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                    </ol>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <img src=\"./img/floor.png\" alt=\"\"><span>å¬å¸ä¼ä¸</span>\r\n");
      out.write("                    <p><span>ç§æ</span><span>é¤é¥®</span><span>ç§æ</span><span>ç§æ</span></p>\r\n");
      out.write("                    <ol>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                    </ol>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <img src=\"./img/floor.png\" alt=\"\"><span>å¬å¸ä¼ä¸</span>\r\n");
      out.write("                    <p><span>ç§æ</span><span>é¤é¥®</span><span>ç§æ</span><span>ç§æ</span></p>\r\n");
      out.write("                    <ol>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                    </ol>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <img src=\"./img/floor.png\" alt=\"\"><span>å¬å¸ä¼ä¸</span>\r\n");
      out.write("                    <p><span>ç§æ</span><span>é¤é¥®</span><span>ç§æ</span><span>ç§æ</span></p>\r\n");
      out.write("                    <ol>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                        <li><span>ç§æä¼ä¸</span></li>\r\n");
      out.write("                    </ol>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"index fl\">\r\n");
      out.write("            <a href=\"index.html\"> é¦é¡µ</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"menus fl\">\r\n");
      out.write("            <a href=\"wx-shoping-list.html\" target=\"_blank\"><p>ç¨åºååº</p></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"menus fl  nav-lists\">\r\n");
      out.write("            <a href=\"sulutions.html\" target=\"_blank\"><p>è¡ä¸æ¹æ¡</p></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"menus fl\">\r\n");
      out.write("            <a href=\"success.html\" target=\"_blank\"><p>æåæ¡ä¾</p></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"menus fl\">\r\n");
      out.write("            <a href=\"tuiguang.html\" target=\"_blank\"><p>æ¨å¹¿è¿è¥</p></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"menus fl\">\r\n");
      out.write("            <a href=\"made.html\" target=\"_blank\"><p>äº§åå®å¶</p></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"but-box join fl\">\r\n");
      out.write("            <a href=\"hezuo.html\" target=\"_blank\">åä½ä»£ç</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"w clearfix\">\r\n");
      out.write("    <div class=\"login-box\">\r\n");
      out.write("        <h2>ä¼åç»å½</h2>\r\n");
      out.write("        <div class=\"inp-box mt\">\r\n");
      out.write("            <input type=\"text\" onblur=\"logins()\" id=\"userNum\" placeholder=\"ææºå·ç \">\r\n");
      out.write("            <p>ææºå·è¾å¥éè¯¯</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"inp-box mt\">\r\n");
      out.write("            <input type=\"password\" id=\"userPwd\" onblur=\"pwds()\" placeholder=\"å¯ç \">\r\n");
      out.write("            <p>å¯ç è¾å¥éè¯¯</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <button type=\"submit\" class=\"sub\">ç»å½</button>\r\n");
      out.write("        <div class=\"login-other clearfix\">\r\n");
      out.write("            <a href=\"reg.html\" class=\"fl\">åå»ºä¸ä¸ªè´¦å·</a>\r\n");
      out.write("            <a href=\"findpwd.html\" class=\"fr\">å¿è®°å¯ç ?</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"black\">\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"https://cdn.bootcss.com/jquery/1.12.2/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.bootcss.com/handlebars.js/4.0.11/handlebars.min.js\"></script>\r\n");
      out.write("<script src=\"./js/pulic.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    function logins() {\r\n");
      out.write("        var that=$(\"#userNum\");\r\n");
      out.write("        if (/^\\d{11}$/.test(that.val())) {\r\n");
      out.write("            that.siblings(\"p\").hide();\r\n");
      out.write("            return true\r\n");
      out.write("        } else {\r\n");
      out.write("            that.siblings(\"p\").show();\r\n");
      out.write("            return false\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    function pwds() {\r\n");
      out.write("        var that=$(\"#userPwd\");\r\n");
      out.write("        if (/^(?![0-9]+$)(?![a-zA-Z]+$)[0-9A-Za-z]{6,21}$/.test(that.val())) {\r\n");
      out.write("            that.siblings(\"p\").hide();\r\n");
      out.write("            return true\r\n");
      out.write("        } else {\r\n");
      out.write("            that.siblings(\"p\").show();\r\n");
      out.write("            return false\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    $(\".sub\").click(function () {\r\n");
      out.write("        if(logins()&&pwds()){\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url:urls+\"/chuizi_wchat/system/appUser/login/json\",\r\n");
      out.write("                type:\"post\",\r\n");
      out.write("                dataType:\"json\",\r\n");
      out.write("                data:{Phone:$(\"#userNum\").val(),password:$(\"#userPwd\").val()},\r\n");
      out.write("                xhrFields: {\r\n");
      out.write("                 withCredentials: true\r\n");
      out.write("                 },\r\n");
      out.write("                crossDomain: true,\r\n");
      out.write("                success:function(d){\r\n");
      out.write("                    console.log(d);\r\n");
      out.write("                    userLogin(function (data) {\r\n");
      out.write("                        if(data.status==\"success\"){\r\n");
      out.write("                            window.location.href=\"./index.html\"\r\n");
      out.write("                        }\r\n");
      out.write("                    });\r\n");
      out.write("//                     window.location.href=\"./index.html\"\r\n");
      out.write("                },\r\n");
      out.write("                error:function (ero) {\r\n");
      out.write("                     console.log(ero)\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    })\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
